Add bill detail page
openpolitica/open-tracker-frontend pull request #102
Opened 2021-12-09 04:21 UTC by paulclindo

Closes #85

2021-12-14 21:18 UTC, redsii commented
@paulclindo no incluimos "proximos pasos" en la cartilla del bill de esta versión

2021-12-14 21:40 UTC, redsii commented
@paulclindo : Omitimos el boton y cambiamos texto de referencia hacia la pagina del congreso. Consultar figma.

2021-12-14 22:58 UTC, redsii commented
@paulclindo el icon del link cambia.

2021-12-23 00:45 UTC, redsii commented
@paulclindo me parece que los iconos de ultima actualizacion y ver bill estan diferentes?

2022-02-02 22:01 UTC, wixo requested changes
Gracias @paulclindo! 🙌 
Solo un cambio de nombre y si puedes descartar los cambios sobre `components/BillCard/index.js` dado que cambios en  https://github.com/openpolitica/open-tracker-frontend/pull/111 puede que generen conflictos en el merge.

2022-02-02 22:01 UTC, wixo commented on pages/proyectos-de-ley/[billId].js
> +export default function Bills({
Pienso que debería llamarse `Bill`

2022-02-04 05:28 UTC, paulclindo commented
Gracias @wixo! Ya lo cambie y también arregle los conflictos, le voy dando merge para seguir con las siguientes tareas 🙌

2022-02-04 05:29 UTC, merged