Sidebar layout congressmen
openpolitica/open-tracker-frontend pull request #17
Opened 2021-08-06 06:59 UTC by paulclindo

Closes https://github.com/openpolitica/open-tracker-frontend/issues/3

Demo: https://www.loom.com/share/665ca5ddd7d34c55be16d7151586e0fc

2021-08-09 04:14 UTC, wixo requested changes
Un par de comentarios y preguntas @paulclindo, gracias!

También, en mobiles lo veo así:
<img width="413" alt="Screen Shot 2021-08-08 at 22 13 06" src="https://user-images.githubusercontent.com/324686/128659752-108d9bdd-b10d-4297-9b1a-e92fc10be9f7.png">

<img width="208" alt="Screen Shot 2021-08-08 at 22 13 50" src="https://user-images.githubusercontent.com/324686/128659792-597b3095-e40b-47e0-a437-ac5be56eff35.png">

2021-08-09 04:14 UTC, wixo commented on theme/sizes.js
> +  sidebarWidth: '183px',
Deberíamos usar `rem`s? 🤔

2021-08-09 04:14 UTC, wixo commented on components/layout/SidebarLayout/SidebarContent.js
> +        h="32px"
estos props puedes ser escritos como tagged templates? es decir como styled components o emotion, pienso que en el tiempo puede confundir tener un prop por una regla de css (que aparte tiene nombres no estándar) / Puedo entender este caso para componentes que no van a ser reusados o actualizados mucho, no sé si este sea el caso.

2021-08-09 04:14 UTC, wixo commented on pages/bancadas/index.js
> +export default function Congresistas() {
```suggestion
export default function CongressGroup() {
```

2021-08-09 04:14 UTC, wixo commented on pages/congresistas/index.js
> +export default function Congresistas() {
```suggestion
export default function Congresspeople() {
```
Sí recomendaría mantener los nombres en inglés, igual para los directorios. Vamos a necesitar un diccionario / glosario de traducciones.

2021-08-09 06:13 UTC, paulclindo commented
@wixo gracias! Sobre los icons, era por el script de SVGO que removía los fill and strokes y removía las dimensiones, le he dado disable a esas config y le di push con los icons que me ha generado. 
Sobre usar rem, px o en general sobre medidas, seria bueno darle una conversación y tener convenciones, así como también al tema de si usar styles en base a props(styled-system) o pure styled components, creo que tienen ambas pros y const, y seria bueno verlo con el equipo de front. Te parece?

2021-08-09 23:07 UTC, wixo commented on components/layout/SidebarLayout/SidebarContent.js
> +        px={2}
```suggestion
        px="2"
```

2021-08-11 23:33 UTC, wixo approved these changes
Gracias @paulclindo!

2021-08-11 23:33 UTC, merged