Parliamentary group card
openpolitica/open-tracker-frontend pull request #19
Opened 2021-08-09 18:44 UTC by AlmeAld

closes #14

2021-08-11 23:37 UTC, wixo requested changes
Gracias @AlmeAld, te dejé unos comentarios, también noté que el padding me parece no está siguiendo las medidas del diseño.
<img width="201" alt="Screen Shot 2021-08-11 at 17 35 52" src="https://user-images.githubusercontent.com/324686/129116993-839b470d-9c1e-40f5-bf8f-fbcc00f8059b.png">

2021-08-11 23:37 UTC, wixo commented on components/ParliamentaryGroupCard/index.js
> +      pt="20px"
Justo decidimos preferentemente usar las medidas de Chakra y luego rems, por favor actualizar los valores en px.

2021-08-11 23:37 UTC, wixo commented on components/ParliamentaryGroupCard/index.js
> +      <CUI.Image w={16} mx="auto" src={logoParty} />
```suggestion
      <CUI.Image w="16" mx="auto" src={logoParty} />
```
Así para todos los números porfa.

2021-08-12 17:33 UTC, AlmeAld commented on components/ParliamentaryGroupCard/index.js
> +      pt="20px"
@wixo hice esas correcciones en el commit 'fix sizes'
![image](https://user-images.githubusercontent.com/60791759/129242319-a5659f4b-600e-4a50-8760-86ecd948a1ce.png)

2021-08-12 19:39 UTC, wixo commented on components/ParliamentaryGroupCard/index.js
> +      pt="20px"
Gracias @AlmeAld, puedes hacer rebase con `staging` y hacer el mismo tipo de cambios para https://github.com/openpolitica/open-tracker-frontend/pull/20, gracias!

2021-08-23 18:18 UTC, paulclindo requested changes

2021-08-23 18:18 UTC, paulclindo commented on components/ParliamentaryGroupCard/index.js
> +        color="#1A1A1A">
```suggestion
        fontWeight="semibold"
        color="secondary.700">
```

2021-08-23 18:18 UTC, paulclindo commented on components/ParliamentaryGroupCard/index.js
> +      <CUI.Image w="16" mx="auto" src={logoParty} />
```suggestion
      <CUI.Image w="12" mx="auto" mb="2" src={logoParty} />
```

2021-08-23 18:18 UTC, paulclindo commented on components/ParliamentaryGroupCard/index.js
> +      pb="6"
Tratemos de ajustar los spacings en base 4 para no lidiar con decimales e usar las medidas de CUI antes de rem
```suggestion
      px="5"
      pt="6"
      pb="4"
```

2021-08-24 04:06 UTC, paulclindo commented
LGTM!

2021-08-24 04:07 UTC, merged