Integrate congresspeople endpoint
openpolitica/open-tracker-frontend pull request #22
Opened 2021-08-28 05:56 UTC by paulclindo

Closes https://github.com/openpolitica/open-tracker-frontend/issues/5

TODO: 
- Conversar la manera de data fetching (CSR, SSR)
- UI: Congressperson card en mobile, breadcrumb, select component

2021-08-28 16:36 UTC, wixo commented on utils/congresspeople.js
> +    'https://api.dev.congreso.openpolitica.com/api/congressperson',
Filtrar por `position_elected`

2021-08-31 03:01 UTC, wixo requested changes
Gracias @paulclindo, 2 temas para conversarlo.

2021-08-31 03:01 UTC, wixo commented on utils/misc.js
> +export const capitalizeStrings = string =>
Si vamos a considerar tener una carpeta de functions de utilidad, podemos tener 1 archivo por función? así podemos agregarle tests, ejemplo: `utils/${capitalizeNames.js, capitalizeNames.test.js}`
También, podemos agregar un test para esta función, que me parece puede tener un nombre más específico como: `capitalizeNames`.
Y por último si puedes considerar omitir capitalizar conectores como en "Paola Del Campo" sería "Paola del Campo" como se hizo en open-wizard https://github.com/openpolitica/open-wizard/blob/staging/components/Steps/PartyResults/startCasePeruvianRegions.js

2021-08-31 03:01 UTC, wixo commented on utils/congresspeople.js
> +async function getCongresspeople() {
Qué te parece tener todo este código en el propio `getStaticProps` no sé donde vayamos a reusar esta llamada en el futuro, considerar https://github.com/openpolitica/open-tracker-frontend/pull/21/files#diff-35b744f2be433f69bbb3a5aef4e20ced3ddd58178491f9b037368fbb4aacd3a9R54

2021-09-01 23:05 UTC, paulclindo commented on utils/misc.js
> +export const capitalizeStrings = string =>
@wixo Si me parece bien, podría ser una solución para manejar los tests para cada function. Por otro lado, no sé si es necesario tener estos functions que son muy pequeños en un archivo único para cada uno y para sus tests. Ultimamente he estado trabajando con organizar los files de esta manera: 

```
/utils
     /__tests__
     --- ...
     --- misc.js
--- ...
--- misc.js
```

Y se me hizo mas sencilla de ubicar código de components, tests, etc, y ya no creo extra files siempre en cuando se mantenga la misma logica/funcionalidad dentro del archivo. Lo mismo podríamos hacer para test en components siempre que sea necesario hacerle test.  Te parece bien esa forma de estructurar o vamos por 

```
/utils
--- capitalizeNames.js
--- capitalizeNames.test.js
--- abcFunction.js
--- abcFunction.test.js
```

Ahora veo lo de omitir el cap en algunos casos, me guiare de open wizard 👍

2021-09-01 23:09 UTC, paulclindo commented on utils/congresspeople.js
> +async function getCongresspeople() {
Si justo lo estaba haciendo de esa manera porque no veía donde reutilizarlo pero lo moví a `/utils` porque para la pagina de cada congresista necesitaba llamar la misma function para iterarla y obtener sus cv_ids https://github.com/openpolitica/open-tracker-frontend/pull/23/files#diff-876057bfed06dcc855d033b35715145f39862c7d7e7d4d0e37ebf47845b1b6bcR55

2021-09-01 23:10 UTC, paulclindo commented on utils/congresspeople.js
> +async function getCongresspeople() {
Pero igual ahora corrijo usando env variables para las api urls

2021-09-02 02:02 UTC, wixo commented on utils/misc.js
> +export const capitalizeStrings = string =>
Hola @paulclindo entiendo el argumento pero también pienso que al estar pensando en componentes, deberíamos tratar de mantener la lógica cercana, por eso usamos folders para tener archivos que interactúan entre sí, `index.js`, `styles.js`, `index.test.js`, `[funcion-utilitaria].js`. Claro que la pregunta está dónde poner lógica que se usa en varios lados. Por eso tenemos `globalStyles` y demás, también deberíamos preferir usar libraries que hacen este trabajo por nosotros. Por ejemplo podríamos tener nuestro propio package de funciones helpers y solo instalarlo y hacerle import. Todo esto es un ideal pero ante la falta todavía estaría a favor de tener toda la lógica referente al componente cercana a este.

Pensando más en `/utils`, iría con la segunda opción ya que nuestros componentes seguirían esa estructura también. luego podríamos tener un `index.js` en `/utils` para poder hacer imports.

¿Qué te parece?

2021-09-02 02:09 UTC, wixo commented on utils/congresspeople.js
> +async function getCongresspeople() {
Como mencioné en otro PR pienso que los fetchs deberían ser lo más simples y no ser wrappeadas en funciones que luego crean desviación (otro lugar a donde ver y hacer debug). Por ahora lo tendría en el mismo `getStaticProps` hasta ver hacia dónde crece el código.

2021-09-02 23:21 UTC, paulclindo commented on utils/misc.js
> +export const capitalizeStrings = string =>
Dale, vamos con esa estructura

2021-09-11 22:09 UTC, wixo approved these changes
Gracias @paulclindo! 🙌

2021-09-11 22:15 UTC, merged