Tab panel
openpolitica/open-tracker-frontend pull request #36
Opened 2021-09-13 06:01 UTC by AlmeAld

Closes #10 
Closes #11

2021-09-13 06:09 UTC, paulclindo approved these changes
LGTM! 🚀

2021-09-13 19:55 UTC, wixo requested changes
Muchas gracias @AlmeAld solo unas cosita de estilo de código y que consideremos usar libraries externos 🙌

2021-09-13 19:55 UTC, wixo commented on components/CongresspersonInfoTab/index.js
> +const mapEducationLevelLabel = {
Creo que podríamos llamarlo `educationLevelLabelMap`, tener el `map` al inicio lo puede hacer confundir con el verbo.

2021-09-13 19:55 UTC, wixo commented on components/CongresspersonInfoTab/index.js
> +            label=" LUGAR DE RESIDENCIA"
Es necesario ese espacio?
```suggestion
            label="LUGAR DE RESIDENCIA"
```

2021-09-13 19:55 UTC, wixo commented on pages/congresistas/[congresspersonSlug].js
> +const groupBy = (items, key) =>
Es necesario tener esta función cuando podemos tener un library de helpers como `npm install lodash.groupby`?

2021-09-13 19:55 UTC, wixo commented on pages/congresistas/[congresspersonSlug].js
> +    (result, item) => ({
Si es el caso, `result` podría llamarse `accumulator` o `prev`, result me hace pensar del resultado de un _fetch_.

2021-09-13 19:55 UTC, wixo commented on pages/congresistas/[congresspersonSlug].js
> +const getAge = dateString => {
Es tan específica esta lógica que necesitamos una función propia? no podemos usar un library como data.fns?

2021-09-13 19:55 UTC, wixo commented on pages/congresistas/[congresspersonSlug].js
> +  const ageDifMs = Date.now() - birthday.getTime();
`difference` generalmente se abrevia como `diff`, puede que lo haga más fácil de leer.

2021-09-16 02:57 UTC, wixo approved these changes
Gracias @AlmeAld! 🙌

2021-09-16 02:57 UTC, merged