add footer component
openpolitica/open-tracker-frontend pull request #90
Opened 2021-11-12 01:39 UTC by AlmeAld

2021-11-12 20:50 UTC, wixo requested changes
Gracias @AlmeAld! dejé unas preguntas.

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +      pl={{ base: '6', md: 'calc(var(--chakra-sizes-sidebarWidth) + 6px)' }}>
6px o 0.375rem? 😅

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +        <CUI.Stack spacing="2" maxW="32%">
podemos considerar un `vw` en vez de un porcentaje, o sí tiene más sentido el porcentaje?

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +    <CUI.Link
Qué nos impide usar aquí `NextCUILink`?

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +              label="Linkedin"
```suggestion
              label="LinkedIn"
```
?

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +              }>
```suggestion
              href="https://www.linkedin.com/company/open-pol%C3%ADtica/mycompany/">
```

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +              href={'https://twitter.com/openpolitica?lang=es'}>
```suggestion
              href="https://twitter.com/openpolitica?lang=es">
```

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +              href={'https://www.instagram.com/open.politica/?hl=es'}>
```suggestion
              href="https://www.instagram.com/open.politica/?hl=es">
```

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +            © 2021 Open Política. Todos los derechos reservados.
Ya pregunté si somos Copyright 😅

2021-11-12 20:50 UTC, wixo commented on components/layout/Footer.js
> +                height: '56px',
```suggestion
                height: '3.5rem',
```
?

2021-11-12 21:53 UTC, paulclindo commented on components/layout/Footer.js
> +      <CUI.VisuallyHidden>{label}</CUI.VisuallyHidden>
Esto es genial! 🚀 Deberíamos empezar a usar más seguido este componente `VisuallyHidden` por accesibilidad, tenemos algunos issues en la app

2021-11-13 16:25 UTC, wixo commented on components/layout/Footer.js
> +      <CUI.VisuallyHidden>{label}</CUI.VisuallyHidden>
Genial!, creo que esto lo podemos usar en https://github.com/openpolitica/open-tracker-frontend/issues/88 cc: @LuighiV

2021-11-13 16:28 UTC, AlmeAld commented on components/layout/Footer.js
> +      pl={{ base: '6', md: 'calc(var(--chakra-sizes-sidebarWidth) + 6px)' }}>
 😅

2021-11-15 00:13 UTC, AlmeAld commented on components/layout/Footer.js
> +    <CUI.Link
```NextCUILink``` son para páginas dentro de nuestra aplicación de next.
```CUI.Link``` para páginas externas.  😁

2021-11-16 20:51 UTC, wixo approved these changes
Gracias @AlmeAld! 🙌

2021-11-16 20:51 UTC, merged